### ISSUE TITLE
Trouble compiling xrEngine

### ISSUE THREAD

**Issue by ghost** [OpenXRay/xray-15#11]
1>x_ray.cpp(399): error C2065: 'hCheckPresenceMutex' : undeclared identifier
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

Don't know what's causing this.

**Comment by nitrocaster** [comment]
That's a typo (my bad).

Line 399: should be CloseHandle(presenceMutex);
