### ISSUE TITLE
oalib_mt.lib

### ISSUE THREAD

**Issue by ghost** [OpenXRay/xray-15#12]
When trying to compile xrEngine, it says it can't find oalib_mt.lib. I downloaded OpenAutomate, and have it's libs and includes selected already. I tried rebuilding OpenAutomate but it didn't generate this file either. It doesn't seem to exist.

**Comment by nitrocaster** [comment]
Make sure that TargetName for Release Multithreaded configuration is oalib_mt.lib.

**Comment by ghost** [comment]
That worked, thank you again for answering all my dumb questions.
