### ISSUE TITLE
xrGame compile issue

### ISSUE THREAD

**Issue by ghost** [OpenXRay/xray-15#13]
Hopefully this will be the very final compilation issue I bug you with as I compiled every other dll fine.

I get this at the end of trying to compile xrGame.dll:

1>  Generating Code...
1>  cximage.lib(xmemfile.obj) : MSIL .netmodule or module compiled with /GL found; restarting link with /LTCG; add /LTCG to the link command line to improve linker performance
1>LINK : fatal error LNK1104: cannot open file 'LIBC.lib'
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

Any thoughts?

**Comment by ghost** [comment]
Scratch that, I added it to ignored dependancies under Linker.

Now I get this:
1>libjpeg.lib(jerror.obj) : error LNK2001: unresolved external symbol __iob
1>E:\dev\xray-master\xray-master\cs\binaries\Release\xrGame.dll : fatal error LNK1120: 1 unresolved externals
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by nitrocaster** [comment]
Where did you get libjpeg.lib? Compiled by yourself or downloaded from somewhere?
Maybe this will help: http://social.msdn.microsoft.com/Forums/vstudio/en-US/8846b4fb-6880-4583-a222-fe7c6615b66a/link-error-unresolved-external-symbol-iob

**Comment by ghost** [comment]
I downloaded it from here since I don't know how to compile it without Visual Studio: http://www.stillhq.com/panda/panda-documentation/000010.html

**Comment by nitrocaster** [comment]
Ok, you can take my project here: https://dl.dropboxusercontent.com/u/63973281/dev/xray/jpeg.7z
Libraries included.

**Comment by ghost** [comment]
That worked, and I finally have all dll's and the exe compiled....and then I run into a new problem: http://imgur.com/jgdOTPP

Sorry again for continuing to ask questions, as you can tell I'm new at this.

**Comment by nitrocaster** [comment]
That's weird, because BT_\* functions are exported from BugTrap.dll, not from xrCore.dll. Make sure you don't use old libraries.

**Comment by ghost** [comment]
You just solved it. I forgot to include the new bugtrap dll. Game runs fine now. Time to add my changes :)
