### ISSUE TITLE
Bizzare problem

### ISSUE THREAD

**Issue by ghost** [OpenXRay/xray-15#14]
Although the source has been compiling for me just fine for a while, all of a sudden I'm getting the following error when trying to start a new game:

FATAL ERROR

[error]Expression    : xml_doc.NavigateToNode(path,index)
[error]Function      : CUIXmlInit::InitWindow
[error]File          : ui\UIXmlInit.cpp
[error]Line          : 88
[error]Description   : XML node not found
[error]Argument 0    : ui_inv_outfit_radiation_protection
[error]Argument 1    : ui\actor_menu_item_16.xml

---

Do you have any idea what could cause this? I haven't modified UIOutfitInfo.cpp which seems to contain this. I have modified xrGame, but not in any way that should disrupt UI (added actor shadow to R2/R3, added new reload sound type to WeaponMagazined, unlocked fov command).

Any ideas what could cause this? I'm not sure the exact commit I'm using, it's at least 4-5 commits old now, but this is the first compile where I've had trouble like this.

**Comment by nitrocaster** [comment]
Try to debug it and see why does the game try to load it from ui\actor_menu_item_16.xml.
ui_inv_outfit_radiation_protection really shouldn't be there.

**Comment by ghost** [comment]
I had trouble compiling the debug files, so instead I downloaded the latest Git, added my changes and compiled. The issue no longer exists. Very bizarre error.
