### ISSUE TITLE
dxguid.lib troubles

### ISSUE THREAD

**Issue by andrew-boyarshin** [OpenXRay/xray-15#5]
# EN

Hello!
I have troubles with compiling X-Ray Engine 1.5.

```
error LNK2001: неразрешенный внешний символ "_CLSID_DirectPlay8Address"   E:\GIT\xray\cs\engine\xrNetServer\NET_Client.obj    xrNetServer
```

And some more lines like that line above.
I tried to find dxguid.lib in Windows Kit 7.0, 7.1, but i didn't find it. I found it in 8.0 and 8.1, but I am not sure, can I use it. Can you please give link to that file or help me finding it?
# RU

Добрый день!
У меня возникли проблемы с компиляцией этого движка.

```
error LNK2001: неразрешенный внешний символ "_CLSID_DirectPlay8Address"   E:\GIT\xray\cs\engine\xrNetServer\NET_Client.obj    xrNetServer
```

И другие ошибки, связанные с DirectPlay8. Я не нашел dxguid.lib ни в Windows Kit 7.0, ни в 7.1. Зато нашел в 8.0 и 8.1. Можно ли использовать их? Если нет, то скиньте ссылку на скачивание нужного dxguid.lib.

**Comment by nitrocaster** [comment]
Hi,
Follow instructions in build.txt: https://github.com/nitrocaster/xray/blob/master/build.txt
In short - take dxguid.lib from your Windows SDK 8.x.

**Comment by andrew-boyarshin** [comment]
@nitrocaster, можно по русски, английский только для соблюдения стиля GitHub.
Я как раз не знал, можно ли юзать из Windows SDK 8.x. Взял - и осталось пофиксить еще пару ошибок компиляции сторонних библиотек.
Спасибо!
